### ISSUE TITLE
Missing "ignore" option in config

### ISSUE THREAD

**Issue by Hecsall** [amoussard/sftp-deployment#118] opened 2016-03-13 22:34 UTC
At the moment, in the deployment-config.json there is no option to ignore a specific file upload or a specific path upload. Uploading even the config file is a big problem because everyone can access the file obtaining the ftp password. Then, the possibility to ignore some file in the upload process would be very interesting and appreciated. Hope you can fix this as soon as possible, thanks. @amoussard

**Comment by amoussard** [comment] 2016-05-01 13:54
Hi @DeSiden,

It's effectively a nice feature.
I will try to add it in the next release.

Thank you for using my package.

**Comment by amoussard** [comment] 2016-05-01 15:20
Duplicate of #116 #113 #107 #100 #97

**Closed** 2021-06-16 20:52 UTC
Labels: duplicate, enhancement
